config/routes.rb
Rails.application.routes.draw do
  
  

 
  resources :employers do
    resources :employees do
      resources :leaves
    end
  end

  devise_for :users, :controllers => {registrations: 'registrations'}

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "employees#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
    belongs_to :employer
end

app/models/employer.rb
class Employer < ApplicationRecord
    has_many :employees , dependent: :destroy
end

app/models/leave.rb
class Leave < ApplicationRecord
 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include Pundit

  before_action :authenticate_user!

  protect_from_forgery with: :exception
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employer = Employer.find_by(id: params[:employer_id])
    @employee = Employee.new
    @user = User.find_by(id: params[:user_id])
  end
  

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create 
    # @user = User.create(user_params)                 
    @employer = Employer.find_by(id: params[:employer_id])
    @employee = @employer.employees.new(employee_params)
    # @user = User.find_by(id: params[:user_id])
    # @employee = @user.employee.new(employee_params)
    respond_to do |format|
      if @employee.save
        puts @employer.inspect
        format.html { redirect_to employer_employee_path(id: params[:employer_id]), notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employer_employee_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      puts params.inspect
      # @employee = Employee.find(params[:id])
      
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:fname, :lname, :emp_no, :date_of_joining, :date_of_termination, :department, :designation, :lead, :manager, :active, :user_id, :email)
    end

    def user_params
      params.require(:employee).permit(:fname, :lname, :emp_no, :date_of_joining, :date_of_termination, :department, :designation, :lead, :manager, :active, :user_id, :email)
    end

  end

app/controllers/leaves_controller.rb
class LeavesController < ApplicationController
  before_action :set_leave, only: [:show, :edit, :update, :destroy]

  # GET /leaves
  # GET /leaves.json
  def index
    @leaves = Leave.all
  end

  # GET /leaves/1
  # GET /leaves/1.json
  def show
  end

  # GET /leaves/new
  def new
    @employee = Employee.find_by(id: params[:employee_id])
    @leave = Leave.new
  end

  # GET /leaves/1/edit
  def edit
  end

  # POST /leaves
  # POST /leaves.json
  def create
    @employee = Employee.find_by(id: params[:employee_id])
    @leave = @employee.leaves.new(leave_params)

    respond_to do |format|
      if @leave.save
        format.html { redirect_to @leave, notice: 'Leave was successfully created.' }
        format.json { render :show, status: :created, location: @leave }
      else
        format.html { render :new }
        format.json { render json: @leave.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leaves/1
  # PATCH/PUT /leaves/1.json
  def update
    respond_to do |format|
      if @leave.update(leave_params)
        format.html { redirect_to @leave, notice: 'Leave was successfully updated.' }
        format.json { render :show, status: :ok, location: @leave }
      else
        format.html { render :edit }
        format.json { render json: @leave.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leaves/1
  # DELETE /leaves/1.json
  def destroy
    @leave.destroy
    respond_to do |format|
      format.html { redirect_to leaves_url, notice: 'Leave was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_leave
      @leave = Leave.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def leave_params
      params.require(:leave).permit(:employee_id, :leave_from_date, :leave_to_date, :reason, :no_of_days)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    
      private
    
      def sign_up_params
        params.require(:user).permit(:first_name, :last_name, :phn_no, :email, :password, :password_confirmation, :address, :role, :active, :date_of_birth)
      end
    
      def account_update_params
        params.require(:user).permit(:first_name, :last_name, :phn_no, :address, :role, :active, :date_of_birth,
        employee_attributes: [ :id, :fname, :lname, :emp_no, :date_of_joining, :date_of_termination, :department, :designation, :lead, :manager ])
      end
    end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/employers_helper.rb
module EmployersHelper
end

app/helpers/leaves_helper.rb
module LeavesHelper
end

app/views/employees/_form.html.erb
<%= form_for @employee, :url => employer_employees_path, :html => { :class => "form-horizontal employee" }, :method => "post" do |f| %>
<%# form_for employer_employees_path(params[:employer_id]), :html => { :class => "form-horizontal employee" }  %>
  <% if @employee.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @employee.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :fname, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :fname, :class => 'form-control' %>
    </div>
    <%=f.error_span(:fname) %>
  </div>
  <div class="form-group">
    <%= f.label :lname, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :lname, :class => 'form-control' %>
    </div>
    <%=f.error_span(:lname) %>
  </div>
  <div class="form-group">
    <%= f.label :emp_no, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :emp_no, :class => 'form-control' %>
    </div>
    <%=f.error_span(:emp_no) %>
  </div>
  <div class="form-group">
    <%= f.label :date_of_joining, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.date_field :date_of_joining, :class => 'form-control' %>
    </div>
    <%=f.error_span(:date_of_joining) %>
  </div>
  <div class="form-group">
    <%= f.label :date_of_termination, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.date_field :date_of_termination, :class => 'form-control' %>
    </div>
    <%=f.error_span(:date_of_termination) %>
  </div>


    <div class="form-group">
    <%= f.label :email, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.email_field :email, :class => 'form-control' %>
    </div>
    <%=f.error_span(:email) %>
  </div>


  <div class="form-group">
    <%= f.label :department, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :department, :class => 'form-control' %>
    </div>
    <%=f.error_span(:department) %>
  </div>
  <div class="form-group">
    <%= f.label :designation, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :designation, :class => 'form-control' %>
    </div>
    <%=f.error_span(:designation) %>
  </div>
  <div class="form-group">
    <%= f.label :lead, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :lead, :class => 'form-control' %>
    </div>
    <%=f.error_span(:lead) %>
  </div>
  <div class="form-group">
    <%= f.label :manager, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :manager, :class => 'form-control' %>
    </div>
    <%=f.error_span(:manager) %>
  </div>
  <div class="form-group">        
    <%= f.label :active, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :active, :class => 'form-control' %>
    </div>
    <%=f.error_span(:active) %>
  </div>

   

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit "submit", :class => 'btn btn-primary'  %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                employer_employees_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>   

app/views/employees/edit.html.erb
<%- model_class = Employee -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/employees/index.html.erb
<%- model_class = Employee -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%=model_class.human_attribute_name(:fname) %></th>
      <th><%=hidden_field_tag (model_class.human_attribute_name(:lname)) %></th>
      <th><%= model_class.human_attribute_name(:emp_no) %></th>
      <th><%= model_class.human_attribute_name(:date_of_joining) %></th>
      <th><%= model_class.human_attribute_name(:date_of_termination) %></th>
      <th><%= hidden_field_tag (model_class.human_attribute_name(:department)) %></th>
      <th><%= model_class.human_attribute_name(:designation) %></th>
      <th><%=hidden_field_tag ( model_class.human_attribute_name(:lead)) %></th>
      <th><%= model_class.human_attribute_name(:manager) %></th>
      <th><%=hidden_field_tag ( model_class.human_attribute_name(:active)) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @employees.each do |employee| %>
      <tr>
       <%# <td><%= link_to employee.id, employee_path(employee) %></td>  
        <td><%=employee.fname%></td>
        <td><%=hidden_field_tag (employee.lname) %></td>
        <td><%= employee.emp_no %></td>
        <td><%= employee.date_of_joining %></td>
        <td><%= employee.date_of_termination %></td>
        <td><%=hidden_field_tag ( employee.department) %></td>
        <td><%= employee.designation %></td>
        <td><%=hidden_field_tag (employee.lead)%></td>
        <td><%= employee.manager %></td>
        <td><%=hidden_field_tag ( employee.active) %></td>
        <td><%=l employee.created_at %></td>
        <td>
           <%= link_to t('.show', :default => t("helpers.links.show")), 
                      employer_employee_path(employer_id: params[:employer_id], id: params[:id]), :class => 'btn btn-default btn-xs' %> 
           <%# <%= link_to t('.edit', :default => t("helpers.links.edit")),  %>
                      <%# edit_employee_path(employee), :class => 'btn btn-default btn-xs'  %>
          <%# <%= hidden_field_tag (link_to t('.destroy', :default => t("helpers.links.destroy")), %>
                      employee_path(employee),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' )%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

 <%= link_to t('.new', :default => t("helpers.links.new")),
             new_employer_employee_path(employer_id: current_user.employer),
            :class => 'btn btn-primary' %> 

<div>

  

app/views/employees/new.html.erb
<%- model_class = Employee -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/employees/show.html.erb
<%- model_class = Employee -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:fname) %>:</strong></dt>
  <dd><%= @employee.fname %></dd>
  <dt><strong><%= model_class.human_attribute_name(:lname) %>:</strong></dt>
  <dd><%= @employee.lname %></dd>
  <dt><strong><%= model_class.human_attribute_name(:emp_no) %>:</strong></dt>
  <dd><%= @employee.emp_no %></dd>
  <dt><strong><%= model_class.human_attribute_name(:date_of_joining) %>:</strong></dt>
  <dd><%= @employee.date_of_joining %></dd>
  <dt><strong><%= model_class.human_attribute_name(:date_of_termination) %>:</strong></dt>
  <dd><%= @employee.date_of_termination %></dd>
  <dt><strong><%= model_class.human_attribute_name(:department) %>:</strong></dt>
  <dd><%= @employee.department %></dd>
  <dt><strong><%= model_class.human_attribute_name(:designation) %>:</strong></dt>
  <dd><%= @employee.designation %></dd>
  <dt><strong><%= model_class.human_attribute_name(:lead) %>:</strong></dt>
  <dd><%= @employee.lead %></dd>
  <dt><strong><%= model_class.human_attribute_name(:manager) %>:</strong></dt>
  <dd><%= @employee.manager %></dd>
  <dt><strong><%= model_class.human_attribute_name(:active) %>:</strong></dt>
  <dd><%= @employee.active %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              employer_employees_path(@employee), :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_employer_employee_path(@employee), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              employer_employee_path(@employee),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

<%# <%= link_to t('.apply leaves', :default => t("helpers.links.apply leaves")), 
              new_employee_leave_path(@employee), :class => 'btn btn-default'  %>

app/views/employers/create.html.erb
<h1>Employers#create</h1>
<p>Find me in app/views/employers/create.html.erb</p>

app/views/employers/destroy.html.erb
<h1>Employers#destroy</h1>
<p>Find me in app/views/employers/destroy.html.erb</p>

app/views/employers/edit.html.erb
<h1>Employers#edit</h1>
<p>Find me in app/views/employers/edit.html.erb</p>

app/views/employers/index.html.erb
<h1>Employers#index</h1>
<p>Find me in app/views/employers/index.html.erb</p>

app/views/employers/new.html.erb
<h1>Employers#new</h1>
<p>Find me in app/views/employers/new.html.erb</p>

app/views/employers/show.html.erb
<h1>Employers#show</h1>
<p>Find me in app/views/employers/show.html.erb</p>

app/views/employers/update.html.erb
<h1>Employers#update</h1>
<p>Find me in app/views/employers/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.css">

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "LeaveManagement" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%# <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %> 

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%# <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%# <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%# <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %> 

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%# <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %> 

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

      <%= render partial: "shared/navbar"  %>

    <div class="container">

      <% if notice %> <p class="notice"><%= notice %></p><% end %>
       <% if alert %><p class="alert"><%= alert %></p><% end %>
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2017</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/leaves/_form.html.erb
<%= form_for @leave, url: employee_leaves_path(params[:employee_id]) do |form| %>
  <% if @leave.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(leave.errors.count, "error") %> prohibited this leave from being saved:</h2>

      <ul>
      <% leave.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :employee_id %>
    <%= form.number_field :employee_id, id: :leave_employee_id %>
  </div>

  <div class="field">
    <%= form.label :leave_from_date %>
    <%= form.date_select :leave_from_date, id: :leave_leave_from_date %>
  </div>

  <div class="field">
    <%= form.label :leave_to_date %>
    <%= form.date_select :leave_to_date, id: :leave_leave_to_date %>
  </div>

  <div class="field">
    <%= form.label :reason %>
    <%= form.text_area :reason, id: :leave_reason %>
  </div>

  <div class="field">
    <%= form.label :no_of_days %>
    <%= form.number_field :no_of_days, id: :leave_no_of_days %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/leaves/edit.html.erb
<h1>Editing leave</h1>

<%= render 'form', leave: @leave %>

<%= link_to 'Show', @leave %> |
<%= link_to 'Back', leaves_path %>

app/views/leaves/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Leaves</h1>

<table>
  <thead>
    <tr>
      <th>Employee</th>
      <th>Leave from date</th>
      <th>Leave to date</th>
      <th>Reason</th>
      <th>No of days</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @leaves.each do |leave| %>
      <tr>
        <td><%= leave.employee_id %></td>
        <td><%= leave.leave_from_date %></td>
        <td><%= leave.leave_to_date %></td>
        <td><%= leave.reason %></td>
        <td><%= leave.no_of_days %></td>
        <td><%= link_to 'Show', leave %></td>
        <td><%= link_to 'Edit', edit_leave_path(leave) %></td>
        <td><%= link_to 'Destroy', leave, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New leave', new_leave_path %>

app/views/leaves/new.html.erb
<h1>New leave</h1>

<%= render 'form', leave: @leave %>

<%= link_to 'Back', employees_path(@employee) %>

app/views/leaves/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Leave from date:</strong>
  <%= @leave.leave_from_date %>
</p>

<p>
  <strong>Leave to date:</strong>
  <%= @leave.leave_to_date %>
</p>

<p>
  <strong>Reason:</strong>
  <%= @leave.reason %>
</p>

<p>
  <strong>No of days:</strong>
  <%= @leave.no_of_days %>
</p>

<%= link_to 'Edit', "" %> |
<%= link_to 'Back', leaves_path %>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:encrypted_password) %></th>
      <th><%= model_class.human_attribute_name(:reset_password_token) %></th>
      <th><%= model_class.human_attribute_name(:reset_password_sent_at) %></th>
      <th><%= model_class.human_attribute_name(:remember_created_at) %></th>
      <th><%= model_class.human_attribute_name(:current_sign_in_at) %></th>
      <th><%= model_class.human_attribute_name(:last_sign_in_at) %></th>
      <th><%= model_class.human_attribute_name(:current_sign_in_ip) %></th>
      <th><%= model_class.human_attribute_name(:last_sign_in_ip) %></th>
      <th><%= model_class.human_attribute_name(:first_name) %></th>
      <th><%= model_class.human_attribute_name(:last_name) %></th>
      <th><%= model_class.human_attribute_name(:phn_no) %></th>
      <th><%= model_class.human_attribute_name(:role) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th><%= model_class.human_attribute_name(:active) %></th>
      <th><%= model_class.human_attribute_name(:date_of_birth) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><%= user.email %></td>
        <td><%= user.encrypted_password %></td>
        <td><%= user.reset_password_token %></td>
        <td><%= user.reset_password_sent_at %></td>
        <td><%= user.remember_created_at %></td>
        <td><%= user.current_sign_in_at %></td>
        <td><%= user.last_sign_in_at %></td>
        <td><%= user.current_sign_in_ip %></td>
        <td><%= user.last_sign_in_ip %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.phn_no %></td>
        <td><%= user.role %></td>
        <td><%= user.address %></td>
        <td><%= user.active %></td>
        <td><%= user.date_of_birth %></td>
        <td><%=l user.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      user_path(user), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(user), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>